apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
patches:
- resources_patch.yaml
- hpa_patch.yaml
namespace: hlg
replicas:
- name: product-api
  count: 1
