apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  strategy: {}
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - image: marcosvieirajr/product-api
        name: product-api
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
