# https://stackoverflow.com/questions/56666532/hpa-not-able-to-fetch-metrics-from-prometheus-in-kubernetes

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-api
spec:
  # minReplicas: 3
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-api
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
