name: Main Workflow
on: [push, workflow_dispatch]
    
env:
  ENV_NAME: 'env value'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        go: ['1.17']
    name: Go ${{ matrix.go }} job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go version

      # - name: Sonar
      # - name: Quality gate
      # - name: Build
      # - name: Push to registry
      # - name: Create Git Version